development:
  adapter: postgresql
  database: sample_app_development
  username: vagrant
  pool: 5
  template: template0

test:
  adapter: postgresql
  database: sample_app_test
  username: vagrant
  pool: 5
  template: template0

production:
  adapter: postgresql
  database: sample_app_production
  username: vagrant
  pool: 5
  template: template0