development:
  adapter: postgresql
  database: sample_app_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  database: sample_app_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  database: sample_app_production
  pool: 5
  template: template0
